#!/bin/sh
#
# This script produces a .pkg installable package on a mac.

# Name of the package
PACKAGE=flow3

# Place to install libraries (should be on java.library.path)
LIBDIR=/Library/Java/Extensions 

# Temporary directory to install libraries
TEMPDIR=`pwd`/out

mkdir ${TEMPDIR} && \
cd .. && \
cmake -DLIB_INSTALL_DIR:PATH=${LIBDIR} . && \
make && \
DESTDIR=${TEMPDIR} make install && \
productbuild --root=pkg ${PACKAGE}.pkg

